name: Agent Index Updater

on:
  pull_request:
    types:
      - closed
    paths:
      - "agents/**/*.yaml"
      - "agents/**/*.yml"

jobs:
  update-index:
    runs-on: ubuntu-latest
    # Only run if the PR was merged (not just closed without merging)
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need to fetch all history to ensure we have the latest changes
          fetch-depth: 0
          # Use the token to be able to push changes back
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jsonschema yamale

      - name: Get changed files in PR
        id: changed-files
        run: |
          # Get the list of files changed in this PR
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E "agents/.*\.(yaml|yml)$" || echo "")
          echo "Changed YAML/YML files in agents directory:"
          echo "$CHANGED_FILES"

          # Save the list of changed files for later use
          echo "$CHANGED_FILES" > changed_files.txt

          # Set outputs for use in later steps
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          if [ -n "$CHANGED_FILES" ]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update agent index
        id: update-index
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Updating agent index..."
          echo "Changed files:"
          cat changed_files.txt

          # Make the script executable
          chmod +x tools/agent_manager/manage_agents.sh

          # Capture the current state of agent_index.json
          if [ -f "agent_index.json" ]; then
            cp agent_index.json agent_index.json.before
          fi

          # Run the agent manager script
          ./tools/agent_manager/manage_agents.sh

          # Check if there are changes to commit by comparing files
          if [ -f "agent_index.json.before" ]; then
            if ! cmp -s "agent_index.json.before" "agent_index.json"; then
              echo "index_updated=true" >> $GITHUB_OUTPUT
              echo "Changes detected in agent_index.json, committing..."
              
              # Configure Git
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              
              # Commit and push changes
              git add agent_index.json
              git commit -m "Update agent index after PR #${{ github.event.pull_request.number }} [skip ci]"
              git push
              
              echo "Agent index updated successfully!"
            else
              echo "index_updated=false" >> $GITHUB_OUTPUT
              echo "No changes to agent_index.json detected."
            fi
          else
            # If the file didn't exist before, it's definitely a change
            if [ -f "agent_index.json" ]; then
              echo "index_updated=true" >> $GITHUB_OUTPUT
              echo "agent_index.json created, committing..."
              
              # Configure Git
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              
              # Commit and push changes
              git add agent_index.json
              git commit -m "Create agent index after PR #${{ github.event.pull_request.number }} [skip ci]"
              git push
              
              echo "Agent index created successfully!"
            else
              echo "index_updated=false" >> $GITHUB_OUTPUT
              echo "No agent_index.json file was created."
            fi
          fi

          # Clean up temporary file
          rm -f agent_index.json.before

      - name: Job summary
        run: |
          echo "# Agent Index Update" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.update-index.outputs.index_updated }}" == "true" ]; then
            echo "✅ Agent index was updated successfully." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            echo "The following files triggered this update:" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            
            # Display the list of changed files directly
            if [ -f "changed_files.txt" ]; then
              cat changed_files.txt >> $GITHUB_STEP_SUMMARY
            else
              # Manually list the files from the PR
              FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E "agents/.*\.(yaml|yml)$" || echo "No YAML/YML files changed")
              echo "$FILES" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "```" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ No changes were needed to the agent index." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The agent index is already up to date with the latest changes." >> $GITHUB_STEP_SUMMARY
          fi
