name: Agent YAML Validator

on:
  push:
    paths:
      - "agents/**/*.yaml"
      - "agents/**/*.yml"
  pull_request:
    paths:
      - "agents/**/*.yaml"
      - "agents/**/*.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml yamale

      - name: Find changed YAML files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            agents/**/*.yaml
            agents/**/*.yml

      - name: Validate changed YAML files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Validating changed YAML files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

          # Create a directory for the validation results
          mkdir -p validation_results

          # Initialize error flag
          ERROR_FOUND=0
          ERROR_DETAILS=""

          # Validate each changed file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Validating $file..."
            
            # Run validation and capture output
            VALIDATION_OUTPUT=$(python tools/agent_manager/src/validator.py --yaml-schema schemas/agent.schema.yaml --file $file --tag-definitions tags.json --output-format github-actions --verbose 2>&1)
            
            # Capture exit code
            EXIT_CODE=$?
            
            # Print validation output
            echo "$VALIDATION_OUTPUT"
            
            if [ $EXIT_CODE -ne 0 ]; then
              ERROR_FOUND=1
              
              # Extract detailed error information
              ERROR_DETAILS+="## ❌ Validation failed for $file\n"
              ERROR_DETAILS+="$VALIDATION_OUTPUT\n\n"
              
              # Create GitHub annotation for the error
              echo "::error file=$file::Validation failed for $file. See job summary for details."
            else
              echo "::notice file=$file::Validation successful for $file."
            fi
          done

          # Save error details to a file for the job summary
          if [ $ERROR_FOUND -eq 1 ]; then
            echo -e "$ERROR_DETAILS" > validation_results/errors.md
            exit 1
          fi

      - name: Create job summary with validation errors
        if: failure()
        run: |
          if [ -f "validation_results/errors.md" ]; then
            echo "# YAML Validation Errors" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat validation_results/errors.md >> $GITHUB_STEP_SUMMARY
          fi

      - name: Validate all YAML files (on PR)
        if: github.event_name == 'pull_request'
        run: |
          echo "Validating all agent YAML files..."

          # Run validation and capture output
          VALIDATION_OUTPUT=$(python tools/agent_manager/src/validator.py --yaml-schema schemas/agent.schema.yaml --directory agents --tag-definitions tags.json --output-format github-actions --verbose 2>&1)

          # Capture exit code
          EXIT_CODE=$?

          # Print validation output
          echo "$VALIDATION_OUTPUT"

          if [ $EXIT_CODE -ne 0 ]; then
            echo "## ❌ Validation failed for one or more files" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "$VALIDATION_OUTPUT" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "## ✅ All files validated successfully" >> $GITHUB_STEP_SUMMARY
          fi
